// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa2ZwUZLisKUXaDK5y4lE5qqatvf36t8M',
    appId: '1:151429192003:web:3b22c18064a4d4248ab7f6',
    messagingSenderId: '151429192003',
    projectId: 'objetperdu-a17b5',
    authDomain: 'objetperdu-a17b5.firebaseapp.com',
    storageBucket: 'objetperdu-a17b5.firebasestorage.app',
    measurementId: 'G-KRVE6SKMRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHN1hlbvBmja4mhd3k_spNtNHEmZGn7bs',
    appId: '1:151429192003:android:b0e1feaf3c69d0a48ab7f6',
    messagingSenderId: '151429192003',
    projectId: 'objetperdu-a17b5',
    storageBucket: 'objetperdu-a17b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ZxDlEnKRa7466hBC_pbluNcY1NUsHxk',
    appId: '1:151429192003:ios:926b45767eb5acbb8ab7f6',
    messagingSenderId: '151429192003',
    projectId: 'objetperdu-a17b5',
    storageBucket: 'objetperdu-a17b5.firebasestorage.app',
    iosClientId: '151429192003-gg5h8kkcfje22c2a8muvitaefc8bqpcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.objetsPerdusDuCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ZxDlEnKRa7466hBC_pbluNcY1NUsHxk',
    appId: '1:151429192003:ios:926b45767eb5acbb8ab7f6',
    messagingSenderId: '151429192003',
    projectId: 'objetperdu-a17b5',
    storageBucket: 'objetperdu-a17b5.firebasestorage.app',
    iosClientId: '151429192003-gg5h8kkcfje22c2a8muvitaefc8bqpcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.objetsPerdusDuCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa2ZwUZLisKUXaDK5y4lE5qqatvf36t8M',
    appId: '1:151429192003:web:4e94bb085739a8208ab7f6',
    messagingSenderId: '151429192003',
    projectId: 'objetperdu-a17b5',
    authDomain: 'objetperdu-a17b5.firebaseapp.com',
    storageBucket: 'objetperdu-a17b5.firebasestorage.app',
    measurementId: 'G-Z4R3SZK1K3',
  );
}
